[WIP] Add support for Grid 3
Baton-donation/app pull request #3
Opened 2021-05-13 11:15 UTC by gavinhenderson

Still underdevelopment, just wanted to open a PR so you could follow my work.

2021-05-14 07:49 UTC, gavinhenderson commented
@codetheweb Your code is brilliant 👌  Made adding this source so much easier

2021-05-14 13:31 UTC, gavinhenderson commented
Hey @codetheweb If you have time can you give this PR a review?

I've added a new app to the appFactory. I called it `Grid`. I considered doing a more generic `sqlite` data source but to be honest there is a fair amount of Grid specific code and the sqlite stuff is probably better off just being duplicated if we end up with another sqlite data source.

I also added a warning to the data source screens to mention that this will pull every users history. It is unlikely that anyone will have more than one user that is active but thought we should still call it out.

Any questions or comments to hesitate to ask :)

2021-05-14 22:29 UTC, codetheweb requested changes
Looks pretty good, thanks.

Last thing: several relatively large `.sqlite` files have been added for testing; would it be possible to re-export a smaller subset of data from those files?

2021-05-14 22:29 UTC, codetheweb commented on main/server/apps/grid.ts
> +    const allHashes = hashes.join("");
Might want to hash the list of hashes here instead of concatenating them so the return is a consistent length across providers.

2021-05-14 22:29 UTC, codetheweb commented on package.json
> +    "sqlite3": "^5.0.2",
iirc CI was having issues with versions > 5.0.0, but hopefully it's fixed now.

2021-05-14 22:29 UTC, codetheweb commented on renderer/pages/setup/4.tsx
> +            This will upload phrases from every Grid user on this computer.
Can you reword this slightly to make it clear that the upload doesn't happen immediately? Maybe just change "upload" -> "add".

2021-05-16 08:06 UTC, willwade commented
On the sources list I wonder if it would be possible to put each grid user it finds as a separate source. Rather than currently it puts them all as one source. You’re going to have the odd situation where a device is shared - maybe just on loan - and you might want to remove all the users except one. If it’s a headache I wouldn’t worry. It’s going to be a rare situation.

2021-05-17 11:41 UTC, gavinhenderson commented
@codetheweb and @willwade 

Changes made: 
* Made the sqlite files smaller by removing data we dont need
* Make the hash a standard length by hashing the hashes
* Updated the text (upload -> add)

@willwade - My thinking is we wait and see how much of problem that is? If we are constantly rejecting people from the collection due to not being able to submit because they are on a shared device then we can look into it but I don't think we should pre-empt the problem. Unless you are certain is a common case?

2021-05-17 17:02 UTC, codetheweb approved these changes
LGTM, just waiting on @willwade.

2021-05-17 17:07 UTC, willwade commented
Looks good to me!

2021-05-17 23:50 UTC, merged

2021-05-18 00:09 UTC, codetheweb commented
Published: https://github.com/Baton-donation/app/releases/tag/v0.6.0