Fixes #5
Baton-donation/app pull request #7
Opened 2021-06-01 14:02 UTC by gavinhenderson

Fixes #5 

The grid code was adding a '.' at the end of a phrase that didn't end in a full stop. This caused problems when a phrase ended in any other punctuation.

Rather than a `endswith('.')` we now to a more robust regex check for any kind of punctutation

This PR:
- Adds a failing test
- Adds a test sqlite file
- Makes the punctuation test more robust

2021-06-01 22:11 UTC, codetheweb requested changes
LGTM, only thing is could you re-export a smaller subset of the test file again? (~1.7 MB currently.)

2021-06-02 08:05 UTC, gavinhenderson commented
Good catch! Thats it down to 218KB 👍

2021-06-03 22:32 UTC, codetheweb approved these changes

2021-06-03 22:32 UTC, merged

2021-06-04 01:36 UTC, codetheweb commented
Released in [v0.7.0](https://github.com/Baton-donation/app/releases/tag/v0.7.0).